"""Knowledge source fixtures for the ClearPath seeding pipeline."""
from app.models.knowledge_source import SourceType

# ── Knowledge Sources ─────────────────────────────────────────────────────────
# Each entry has a unique "key" used by RULE_FIXTURES to reference its source_id.
SOURCE_FIXTURES = [
    # ── Australia ─────────────────────────────────────────────────────────────
    {
        "key": "AU_ATO_RESIDENCY",
        "jurisdiction": "AU",
        "title": "ATO — Tax residency guidance for individuals",
        "url": "https://www.ato.gov.au/individuals-and-families/coming-to-australia-or-going-overseas/your-tax-residency/australian-resident-for-tax-purposes",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_CGT",
        "jurisdiction": "AU",
        "title": "ATO — Foreign residents and capital gains tax",
        "url": "https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/foreign-residents-and-capital-gains-tax",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_FRCGW",
        "jurisdiction": "AU",
        "title": "ATO — Foreign Resident Capital Gains Withholding (FRCGW)",
        "url": "https://www.ato.gov.au/individuals-and-families/investments-and-assets/capital-gains-tax/foreign-residents-and-capital-gains-tax/capital-gains-withholding---a-guide-for-conveyancers",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_DEPARTURE",
        "jurisdiction": "AU",
        "title": "ATO — CGT consequences of ceasing to be an Australian resident",
        "url": "https://www.ato.gov.au/individuals-and-families/coming-to-australia-or-going-overseas/leaving-australia-for-an-extended-period/cgt-when-becoming-or-ceasing-to-be-an-australian-resident",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_WHT",
        "jurisdiction": "AU",
        "title": "ATO — Withholding from interest, dividends and royalties paid to non-residents",
        "url": "https://www.ato.gov.au/businesses-and-organisations/international-tax-for-business/in-detail/withholding-from-payments-to-non-residents",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_DIV7A",
        "jurisdiction": "AU",
        "title": "ATO — Division 7A (loans, payments and forgiven debts from private companies)",
        "url": "https://www.ato.gov.au/businesses-and-organisations/private-wealth/private-company-benefits---division-7a-dividends",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_S99B",
        "jurisdiction": "AU",
        "title": "ATO — Section 99B distributions from foreign trusts",
        "url": "https://www.ato.gov.au/individuals-and-families/investments-and-assets/in-detail/foreign-trusts/distributions-from-foreign-trusts",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_HELP",
        "jurisdiction": "AU",
        "title": "ATO — Study and training loan repayments while overseas",
        "url": "https://www.ato.gov.au/individuals-and-families/study-and-training-support-loans/overseas-repayments",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_DASP",
        "jurisdiction": "AU",
        "title": "ATO — Departing Australia Superannuation Payment (DASP)",
        "url": "https://www.ato.gov.au/individuals-and-families/super-for-individuals-and-families/super/withdrawing-and-using-your-super/departing-australia-superannuation-payment-dasp",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_FOREIGN_SUPER",
        "jurisdiction": "AU",
        "title": "ATO — Foreign super fund transfers and applicable fund earnings",
        "url": "https://www.ato.gov.au/individuals-and-families/super-for-individuals-and-families/super/growing-and-keeping-track-of-your-super/transferring-or-consolidating-your-super/transferring-your-super-from-a-foreign-fund",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_TEMP_RES",
        "jurisdiction": "AU",
        "title": "ATO — Temporary residents and foreign-source income concessions",
        "url": "https://www.ato.gov.au/individuals-and-families/coming-to-australia-or-going-overseas/your-tax-residency/temporary-residents",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_ATO_MEDICARE",
        "jurisdiction": "AU",
        "title": "ATO — Medicare Levy and Medicare Levy Surcharge",
        "url": "https://www.ato.gov.au/individuals-and-families/medicare-and-private-health-insurance/medicare-levy-surcharge",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_FIRB",
        "jurisdiction": "AU",
        "title": "FIRB — Foreign Investment Review Board: residential real estate",
        "url": "https://firb.gov.au/guidance-resources/guidance-notes/gn06",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "AU_NSW_DUTY",
        "jurisdiction": "AU",
        "title": "Revenue NSW — Surcharge purchaser duty for foreign persons",
        "url": "https://www.revenue.nsw.gov.au/taxes-duties-levies-royalties/transfer-duty/surcharge-purchaser-duty",
        "source_type": SourceType.legislation,
    },
    {
        "key": "AU_TREASURY_DTA",
        "jurisdiction": "AU",
        "title": "Australian Treasury — Income tax treaties index",
        "url": "https://treasury.gov.au/tax-treaties",
        "source_type": SourceType.treaty,
    },
    {
        "key": "AU_ATO_PE",
        "jurisdiction": "AU",
        "title": "ATO — Permanent establishment for non-residents (PCG 2021/D2 / TR 2002/5)",
        "url": "https://www.ato.gov.au/law/view/document?DocID=TXR/TR20025/NAT/ATO/00001",
        "source_type": SourceType.guidance,
    },
    # ── Singapore ─────────────────────────────────────────────────────────────
    {
        "key": "SG_IRAS_RESIDENCY",
        "jurisdiction": "SG",
        "title": "IRAS — Tax residency and tax rates for individuals",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-residency-and-tax-rates/working-out-my-tax-residency",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_NONRESIDENT",
        "jurisdiction": "SG",
        "title": "IRAS — Tax obligations for non-resident individuals",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/non-residents",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_RATES",
        "jurisdiction": "SG",
        "title": "IRAS — Individual income tax rates (resident progressive scale)",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-residency-and-tax-rates/individual-income-tax-rates",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_FSIE",
        "jurisdiction": "SG",
        "title": "IRAS — Tax treatment of foreign-sourced income remitted to Singapore",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/employees/working-outside-singapore/income-earned-when-working-overseas",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_CLEARANCE",
        "jurisdiction": "SG",
        "title": "IRAS — Tax clearance for foreign and Singapore PR employees (Form IR21)",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/employers/tax-clearance-for-foreign-spr-employees-(ir21)",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_PROPERTY",
        "jurisdiction": "SG",
        "title": "IRAS — Buyer's Stamp Duty and Additional Buyer's Stamp Duty (ABSD)",
        "url": "https://www.iras.gov.sg/taxes/stamp-duty/for-property/buying-or-acquiring-property/additional-buyer's-stamp-duty-(absd)",
        "source_type": SourceType.legislation,
    },
    {
        "key": "SG_IRAS_NOR",
        "jurisdiction": "SG",
        "title": "IRAS — Not Ordinarily Resident (NOR) scheme (last application YA 2020)",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/employees/working-outside-singapore/not-ordinarily-resident-scheme",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_AREA_REP",
        "jurisdiction": "SG",
        "title": "IRAS — Area Representative scheme (employment income apportionment)",
        "url": "https://www.iras.gov.sg/taxes/individual-income-tax/employees/working-outside-singapore/area-representative-scheme",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "SG_IRAS_PROPERTY_GAINS",
        "jurisdiction": "SG",
        "title": "IRAS — Seller's Stamp Duty (SSD) on residential property",
        "url": "https://www.iras.gov.sg/taxes/stamp-duty/for-property/selling-or-disposing-property/seller's-stamp-duty-(ssd)-for-residential-property",
        "source_type": SourceType.legislation,
    },
    {
        "key": "SG_IRAS_CRS",
        "jurisdiction": "SG",
        "title": "IRAS — Common Reporting Standard (CRS) for financial accounts",
        "url": "https://www.iras.gov.sg/taxes/international-tax/common-reporting-standard-(crs)",
        "source_type": SourceType.legislation,
    },
    # ── Hong Kong ─────────────────────────────────────────────────────────────
    {
        "key": "HK_IRD_SALARIES",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Salaries Tax guidance",
        "url": "https://www.ird.gov.hk/eng/tax/ind.htm",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "HK_IRD_PROFITS",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Profits Tax and territorial source principle",
        "url": "https://www.ird.gov.hk/eng/tax/bus.htm",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "HK_IRD_60DAY",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Salaries Tax 60-day visitor exemption (s. 8(1B) IRO)",
        "url": "https://www.ird.gov.hk/eng/pdf/dipn10.pdf",
        "source_type": SourceType.guidance,
    },
    {
        "key": "HK_IRD_FSIE",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Foreign-Sourced Income Exemption (FSIE) regime",
        "url": "https://www.ird.gov.hk/eng/tax/bus_fsie.htm",
        "source_type": SourceType.legislation,
    },
    {
        "key": "HK_IRD_STAMP",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Stamp Duty on property and shares",
        "url": "https://www.ird.gov.hk/eng/tax/sdu.htm",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "HK_IRD_FAMILY_OFFICE",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Tax concession for Family-Owned Investment Holding Vehicles (FIHVs)",
        "url": "https://www.ird.gov.hk/eng/tax/bus_fihv.htm",
        "source_type": SourceType.legislation,
    },
    {
        "key": "HK_IRD_RATES",
        "jurisdiction": "HK",
        "title": "IRD Hong Kong — Salaries Tax rates and standard rate",
        "url": "https://www.ird.gov.hk/eng/pdf/pam61e.pdf",
        "source_type": SourceType.government_guidance,
    },
    # ── UAE ───────────────────────────────────────────────────────────────────
    {
        "key": "UAE_FTA_RESIDENCY",
        "jurisdiction": "UAE",
        "title": "UAE Federal Tax Authority — Tax residency certificate guidance",
        "url": "https://tax.gov.ae/en/services/issuance.of.tax.certificates.aspx",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "UAE_FTA_CORPORATE",
        "jurisdiction": "UAE",
        "title": "UAE Federal Tax Authority — Corporate Tax guidance (effective June 2023)",
        "url": "https://tax.gov.ae/en/taxes/corporate.tax.aspx",
        "source_type": SourceType.legislation,
    },
    {
        "key": "UAE_FTA_SBR",
        "jurisdiction": "UAE",
        "title": "UAE Ministry of Finance — Small Business Relief (Ministerial Decision No. 73 of 2023)",
        "url": "https://mof.gov.ae/corporate-tax-policy/",
        "source_type": SourceType.legislation,
    },
    {
        "key": "UAE_FTA_VAT",
        "jurisdiction": "UAE",
        "title": "UAE Federal Tax Authority — VAT registration and compliance",
        "url": "https://tax.gov.ae/en/taxes/vat.aspx",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "UAE_ESR",
        "jurisdiction": "UAE",
        "title": "UAE Ministry of Finance — Economic Substance Regulations (Cabinet Decision No. 57 of 2020)",
        "url": "https://mof.gov.ae/economic-substance-regulations/",
        "source_type": SourceType.legislation,
    },
    {
        "key": "UAE_DMTT",
        "jurisdiction": "UAE",
        "title": "UAE Ministry of Finance — Domestic Minimum Top-up Tax / OECD Pillar Two (effective Jan 2025)",
        "url": "https://mof.gov.ae/corporate-tax/",
        "source_type": SourceType.legislation,
    },
    {
        "key": "UAE_AU_DTA",
        "jurisdiction": "UAE",
        "title": "Australian Treasury — Australia-UAE tax treaty status",
        "url": "https://treasury.gov.au/tax-treaties/income-tax-treaties",
        "source_type": SourceType.treaty,
    },
    # ── United States ─────────────────────────────────────────────────────────
    {
        "key": "US_IRS_INTERNATIONAL",
        "jurisdiction": "US",
        "title": "IRS — Publication 54: Tax Guide for U.S. Citizens and Resident Aliens Abroad",
        "url": "https://www.irs.gov/publications/p54",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_FINCEN_FBAR",
        "jurisdiction": "US",
        "title": "FinCEN — FBAR filing requirements (FinCEN 114)",
        "url": "https://bsaefiling.fincen.gov/file/fbar",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_PFIC",
        "jurisdiction": "US",
        "title": "IRS — Passive Foreign Investment Company (PFIC) guidance",
        "url": "https://www.irs.gov/instructions/i8621",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_FATCA",
        "jurisdiction": "US",
        "title": "IRS — Form 8938 (FATCA Statement of Specified Foreign Financial Assets)",
        "url": "https://www.irs.gov/businesses/corporations/foreign-account-tax-compliance-act-fatca",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_GILTI",
        "jurisdiction": "US",
        "title": "IRS — GILTI and Subpart F income for US shareholders of CFCs",
        "url": "https://www.irs.gov/forms-pubs/about-form-5471",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_ESTATE_NRA",
        "jurisdiction": "US",
        "title": "IRS — Estate and gift tax for non-resident aliens (US-situs assets)",
        "url": "https://www.irs.gov/individuals/international-taxpayers/some-nonresidents-with-us-assets-must-file-estate-tax-returns",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_EXIT",
        "jurisdiction": "US",
        "title": "IRS — Expatriation Tax under IRC §877A and Form 8854",
        "url": "https://www.irs.gov/individuals/international-taxpayers/expatriation-tax",
        "source_type": SourceType.legislation,
    },
    {
        "key": "US_IRS_TIE_BREAKER",
        "jurisdiction": "US",
        "title": "IRS — Treaty residency tie-breaker (Form 8833)",
        "url": "https://www.irs.gov/forms-pubs/about-form-8833",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_NIIT",
        "jurisdiction": "US",
        "title": "IRS — Net Investment Income Tax (NIIT) under IRC §1411",
        "url": "https://www.irs.gov/individuals/net-investment-income-tax",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_IRS_CLOSER",
        "jurisdiction": "US",
        "title": "IRS — Closer Connection Exception to the Substantial Presence Test (Form 8840)",
        "url": "https://www.irs.gov/individuals/international-taxpayers/conditions-for-a-closer-connection-to-a-foreign-country",
        "source_type": SourceType.government_guidance,
    },
    {
        "key": "US_AU_DTA",
        "jurisdiction": "US",
        "title": "IRS — Australia-United States income tax treaty",
        "url": "https://www.irs.gov/businesses/international-businesses/australia-tax-treaty-documents",
        "source_type": SourceType.treaty,
    },
]
